# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_test',
            new_name='status_text',
        ),
    ]
